import ButtonComp from "@/app/components/Button";
import Counter from "@/app/components/Counter";
import PageTitle from "@/app/components/PageTitle";
import { Metadata } from "next";
import Head from "next/head";
import React from "react";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};
function page() {
  return (
    <div className="container mx-auto">
      <section className="flex justify-center flex-col">
        <PageTitle title="Blogs" isCenter />
        {/* <ButtonComp /> */}
        <div className="flex justify-center gap-5 items-center">
          <Counter />
        </div>
      </section>
    </div>
  );
}

export default page;
